### ISSUE TITLE
flickering

### ISSUE THREAD

**Issue by morenoh149** [JakeSidSmith/react-fastclick#1]
I'm getting lots of flickering throughout my app after adding fastclick on iOS. Could you elaborate on where to use event.preventDefault() you mention in the readme

**Comment by manosim** [comment]
Hey @morenoh149! I managed to remove the flickering at [react-cordova](https://github.com/ekonstantinidis/react-cordova/blob/react-fastclick/www/src/js/pages/home.js#L10-L13). So basically you can do something like that:

```
goToAboutPage: function (event) {
  event.preventDefault();
  this.transitionTo('about');
},
```

@JakeSidSmith can you confirm this?

**Comment by JakeSidSmith** [comment]
~~Yup, @ekonstantinidis is correct. Just call preventDefault on the event of the callback. :)~~

**Comment by JakeSidSmith** [comment]
Just found a nicer solution - you can set the css property `-webkit-tap-highlight-color` to transparent.
Either target `html, body` (to prevent the flickering on all elements) or target the specific element you don't want to flicker e.g. `button`.

``` css
html, body {
  -webkit-tap-highlight-color: transparent;
}
```

**Updated readme.**

**Comment by manosim** [comment]
Yeap can confirm this works great! Tested on iOS! :+1:
