### ISSUE TITLE
React 0.15 - warning when modifying synthetic events

### ISSUE THREAD

**Issue by liu-dongyu** [JakeSidSmith/react-fastclick#28]
When i click `a` element by onClick event, i got a waning like 

warning.js?0260:44 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're adding a new property in the synthetic event object. The property is never released. See https://fb.me/react-event-pooling for more information.

What is that mean and how to solve it?

**Comment by JakeSidSmith** [comment]
Yes, sorry about that. This issue was raised in #27, but not directly related. I'll be looking into this at some point in the next couple of days. :)

**Comment by zxx-abc** [comment]
Still facing this problem when using react-router's '<Link />' tag...
react v15.0.0
react-router v2.0.0 
react-fastclick v2.0.0
