### ISSUE TITLE
React as peer dep

### ISSUE THREAD

**Issue by jondlm** [JakeSidSmith/react-fastclick#40]
I think React should be in the peer deps instead of regular deps.

**Comment by JakeSidSmith** [comment]
I had considered this, but have had so many issues with peerDeps in the past I decided not to. I guess if I set it to `"react": "*"` then people shouldn't have problems resolving dependencies.

**Comment by jondlm** [comment]
Yeah peer deps are a pain but they do correctly represent the relationship react libraries share with with react.

The trouble with keeping it as a regular dep is that it could trigger some builds to install multiple copies of React, which is always a huge pain to diagnose, rather than getting a warning from npm/yarn about having invalid peer deps.

**Comment by JakeSidSmith** [comment]
How about I pin a specific version of React as a devDep (for testing), and set peerDep to `*`?

**Comment by jondlm** [comment]
Yeah, that's what I've seen work with other libraries 👍

**Comment by JakeSidSmith** [comment]
Going to release some changes today (including #42). I'll update the deps also. :)
