### ISSUE TITLE
Remove "engines" from package.json

### ISSUE THREAD

**Issue by geta6** [JakeSidSmith/react-fastclick#45]
This module won't install with `yarn` that seems to be more strict about checking `engines` flags than the `npm` client.

```
$ node --version
v7.4.0

$ yarn
yarn install v0.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error react-fastclick@3.0.0: The engine "node" is incompatible with this module. Expected version "6.9.4".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by JakeSidSmith** [comment]
I had no idea this'd be an issue as:

> Note that, unless the user has set the engine-strict config flag, this field is advisory only.
> engineStrict: This feature was deprecated with npm 3.0.0
[Source](https://docs.npmjs.com/files/package.json)

I haven't used yarn yet, myself. Does yarn have an equivalent that might fix the issue for you? 
This [issue](https://github.com/yarnpkg/yarn/issues/972) says that you can `--ignore-engines`, would that solve your problem?

**Comment by caio-ribeiro-pereira** [comment]
@JakeSidSmith if you remove "engine" will solve better instead fix a node version. Because this is a node's module, the "engine" is useful when you are creating a server and some hosts like Heroku/Openshift use it to setup nodejs according to a fixed version in this property.

**Comment by caio-ribeiro-pereira** [comment]
and please let me know when solve this issue, because I really wanna use this lib in my project https://watchcoins.herokuapp.com thanks!

**Comment by JakeSidSmith** [comment]
Heroku / Openshift wouldn't use this libs engine version though, it'd use the one from your project's package.

I may, however just remove this. Kind of pissed that yarn is messing this up. The engines are only supposed to be guidelines for what version a library is proven to work in. :/

**Comment by caio-ribeiro-pereira** [comment]
Well, if you need the `engine` property, change the fixed version to a flexible one, like: `>= 6.0.0`, or `~6.x.x`,

**Comment by JakeSidSmith** [comment]
I don't want people using 5 or less to have issues though. May just set to `*`. I'll have a think.

**Comment by faceyspacey** [comment]
+1

waiting on this as well

**Comment by caio-ribeiro-pereira** [comment]
me too!
