### ISSUE TITLE
Is this plugin needed if targeting newer mobile devices?

### ISSUE THREAD

**Issue by jfbloom22** [JakeSidSmith/react-fastclick#59]
Any reason I need this plugin if I am targeting newer mobile devices and setting the width to the device width?

This disables the 300ms delay since iOS 9.3 and Chrome 32. 
`<meta name="viewport" content="width=device-width">`

more info:  https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away

**Comment by JakeSidSmith** [comment]
As far as I know, if you are only supporting the latest versions of iOS / Chrome you should be okay. No need for this. 🙂

**Comment by jfbloom22** [comment]
awesome thx!
